// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace Aspose.Jmap;

/// <summary>
/// Standard error shape returned per-id in <c>notCreated</c>, <c>notUpdated</c> or <c>notDestroyed</c>.
/// </summary>
public sealed class SetError
{
    /// <summary>
    /// Error type, e.g. <c>invalidProperties</c>, <c>notFound</c>, <c>forbidden</c>, <c>tooLarge</c>.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type { get; init; } = null!;

    /// <summary>
    /// Optional human‑readable description of the error.
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; }

    /// <summary>
    /// Which properties of the create/update failed, if applicable.
    /// </summary>
    [JsonPropertyName("properties")]
    public IReadOnlyList<string>? Properties { get; init; }
}

/// <summary>
/// Standard top‑level method‑call error, returned as an <c>error</c> method response.
/// </summary>
public sealed class MethodError
{
    /// <summary>
    /// Error type, e.g. <c>unknownMethod</c>, <c>invalidArguments</c>, <c>accountNotFound</c>, <c>serverFail</c>.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type { get; init; } = null!;

    /// <summary>
    /// Optional human‑readable description of the error.
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; }
}

/// <summary>
/// A back‑reference used inside a request argument to point at a value produced by an earlier
/// method call in the same request: <c>{ resultOf, name, path }</c>.
/// </summary>
public sealed class ResultReference
{
    /// <summary>
    /// Identifier of the earlier method call whose result is referenced.
    /// </summary>
    [JsonPropertyName("resultOf")]
    public string ResultOf { get; init; } = null!;

    /// <summary>
    /// Name of the result property to reference.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; init; } = null!;

    /// <summary>
    /// JSON Pointer into the referenced result.
    /// </summary>
    [JsonPropertyName("path")]
    public string Path { get; init; } = null!;
}

/// <summary>
/// Base class for all JMAP‑related exceptions.
/// </summary>
public abstract class JmapException : Exception
{
    /// <summary>
    /// Initializes a new instance of <see cref="JmapException"/>.
    /// </summary>
    protected JmapException() { }

    /// <summary>
    /// Initializes a new instance of <see cref="JmapException"/> with a specified error message.
    /// </summary>
    /// <param name="message">The error message.</param>
    protected JmapException(string? message) : base(message) { }

    /// <summary>
    /// Initializes a new instance of <see cref="JmapException"/> with a specified error message and a reference
    /// to the inner exception that is the cause of this exception.
    /// </summary>
    /// <param name="message">The error message.</param>
    /// <param name="innerException">The inner exception.</param>
    protected JmapException(string? message, Exception? innerException) : base(message, innerException) { }
}

/// <summary>
/// Represents an error returned by the JMAP protocol itself (i.e., a method‑level error response).
/// </summary>
public sealed class JmapProtocolException : JmapException
{
    /// <summary>
    /// The protocol error type (e.g., <c>unknownMethod</c>, <c>invalidArguments</c>).
    /// </summary>
    public string ErrorType { get; }

    /// <summary>
    /// Optional human‑readable description supplied by the server.
    /// </summary>
    public string? Description { get; }

    /// <summary>
    /// Initializes a new instance of <see cref="JmapProtocolException"/>.
    /// </summary>
    /// <param name="errorType">The protocol error type.</param>
    /// <param name="description">Optional description of the error.</param>
    /// <param name="message">Optional custom message; if <c>null</c>, <paramref name="description"/> or <paramref name="errorType"/> is used.</param>
    /// <param name="innerException">Optional inner exception.</param>
    public JmapProtocolException(string errorType, string? description = null, string? message = null, Exception? innerException = null)
        : base(message ?? description ?? errorType, innerException)
    {
        ErrorType = errorType ?? throw new ArgumentNullException(nameof(errorType));
        Description = description;
    }
}

/// <summary>
/// Represents a failure in the underlying transport layer (e.g., network connectivity, HTTP errors).
/// </summary>
public sealed class JmapNetworkException : JmapException
{
    /// <summary>
    /// Initializes a new instance of <see cref="JmapNetworkException"/>.
    /// </summary>
    /// <param name="message">The error message.</param>
    /// <param name="innerException">Optional inner exception that caused the failure.</param>
    public JmapNetworkException(string? message, Exception? innerException = null)
        : base(message, innerException) { }
}
