using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable enable

namespace Aspose.Jmap;

/// <summary>
/// A single email message (RFC 8621 "Email" object). Immutable content (headers, body) plus mutable per‑mailbox metadata (mailboxIds, keywords).
/// </summary>
public class Email
{
    /// <summary>
    /// Server‑assigned identifier.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// Blob id of the full raw RFC 5322 message.
    /// </summary>
    [JsonPropertyName("blobId")]
    public string? BlobId { get; init; }

    /// <summary>
    /// Server‑assigned thread identifier.
    /// </summary>
    [JsonPropertyName("threadId")]
    public string? ThreadId { get; init; }

    /// <summary>
    /// Set of mailbox ids this Email is in.
    /// </summary>
    [JsonPropertyName("mailboxIds")]
    public IReadOnlyDictionary<string, bool> MailboxIds { get; set; } = new Dictionary<string, bool>();

    /// <summary>
    /// Keywords such as $seen, $flagged, $answered, $draft.
    /// </summary>
    [JsonPropertyName("keywords")]
    public IReadOnlyDictionary<string, bool> Keywords { get; set; } = new Dictionary<string, bool>();

    /// <summary>
    /// Server‑assigned size in octets.
    /// </summary>
    [JsonPropertyName("size")]
    public uint? Size { get; init; }

    /// <summary>
    /// Server‑assigned UTC date string when the message was received.
    /// </summary>
    [JsonPropertyName("receivedAt")]
    public string? ReceivedAt { get; init; }

    /// <summary>
    /// Message‑Id header value(s).
    /// </summary>
    [JsonPropertyName("messageId")]
    public IReadOnlyList<string>? MessageId { get; init; }

    /// <summary>
    /// In‑Reply‑To header value(s).
    /// </summary>
    [JsonPropertyName("inReplyTo")]
    public IReadOnlyList<string>? InReplyTo { get; init; }

    /// <summary>
    /// References header value(s).
    /// </summary>
    [JsonPropertyName("references")]
    public IReadOnlyList<string>? References { get; init; }

    /// <summary>
    /// Sender addresses.
    /// </summary>
    [JsonPropertyName("sender")]
    public IReadOnlyList<EmailAddress>? Sender { get; init; }

    /// <summary>
    /// From addresses.
    /// </summary>
    [JsonPropertyName("from")]
    public IReadOnlyList<EmailAddress>? From { get; init; }

    /// <summary>
    /// To addresses.
    /// </summary>
    [JsonPropertyName("to")]
    public IReadOnlyList<EmailAddress>? To { get; init; }

    /// <summary>
    /// Cc addresses.
    /// </summary>
    [JsonPropertyName("cc")]
    public IReadOnlyList<EmailAddress>? Cc { get; init; }

    /// <summary>
    /// Bcc addresses.
    /// </summary>
    [JsonPropertyName("bcc")]
    public IReadOnlyList<EmailAddress>? Bcc { get; init; }

    /// <summary>
    /// Reply‑To addresses.
    /// </summary>
    [JsonPropertyName("replyTo")]
    public IReadOnlyList<EmailAddress>? ReplyTo { get; init; }

    /// <summary>
    /// Subject header.
    /// </summary>
    [JsonPropertyName("subject")]
    public string? Subject { get; init; }

    /// <summary>
    /// Sent date (RFC 3339 string).
    /// </summary>
    [JsonPropertyName("sentAt")]
    public string? SentAt { get; init; }

    /// <summary>
    /// Body structure of the email.
    /// </summary>
    [JsonPropertyName("bodyStructure")]
    public EmailBodyPart? BodyStructure { get; init; }

    /// <summary>
    /// Mapping of body part ids to their values.
    /// </summary>
    [JsonPropertyName("bodyValues")]
    public IReadOnlyDictionary<string, EmailBodyValue>? BodyValues { get; init; }

    /// <summary>
    /// Text body parts.
    /// </summary>
    [JsonPropertyName("textBody")]
    public IReadOnlyList<EmailBodyPart>? TextBody { get; init; }

    /// <summary>
    /// HTML body parts.
    /// </summary>
    [JsonPropertyName("htmlBody")]
    public IReadOnlyList<EmailBodyPart>? HtmlBody { get; init; }

    /// <summary>
    /// Attachment body parts.
    /// </summary>
    [JsonPropertyName("attachments")]
    public IReadOnlyList<EmailBodyPart>? Attachments { get; init; }

    /// <summary>
    /// Indicates whether the email has any attachments.
    /// </summary>
    [JsonPropertyName("hasAttachment")]
    public bool? HasAttachment { get; init; }

    /// <summary>
    /// Preview text generated by the server.
    /// </summary>
    [JsonPropertyName("preview")]
    public string? Preview { get; init; }
}

/// <summary>
/// Represents the value of a body part in an Email.
/// </summary>
public class EmailBodyValue
{
    /// <summary>
    /// The actual value of the body part.
    /// </summary>
    [JsonPropertyName("value")]
    public string? Value { get; init; }

    /// <summary>
    /// True if there was an encoding problem.
    /// </summary>
    [JsonPropertyName("isEncodingProblem")]
    public bool? IsEncodingProblem { get; init; }

    /// <summary>
    /// True if the value was truncated.
    /// </summary>
    [JsonPropertyName("isTruncated")]
    public bool? IsTruncated { get; init; }
}
