// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using Xunit;
using Aspose.Jmap;

#nullable enable

namespace Aspose.Jmap.Tests;

/// <summary>
/// Tests for the shared JMAP types defined in <see cref="CommonTypes.cs"/>.
/// </summary>
public class CommonTypesTests
{
    private static readonly JsonSerializerOptions _jsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        WriteIndented = false,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
    };

    [Fact]
    public void SetError_Serialization_WithAllFields_ShouldMatchJson()
    {
        var error = new SetError
        {
            Type = "invalidProperties",
            Description = "Invalid property values",
            Properties = new List<string> { "subject", "from" }
        };

        string json = JsonSerializer.Serialize(error, _jsonOptions);
        var doc = JsonNode.Parse(json)!.AsObject();

        Assert.Equal("invalidProperties", (string?)doc["type"]);
        Assert.Equal("Invalid property values", (string?)doc["description"]);
        Assert.NotNull(doc["properties"]);
        var props = doc["properties"]!.AsArray()
            .Select(p => p.GetValue<string>())
            .ToList();
        Assert.Equal(2, props.Count);
        Assert.Contains("subject", props);
        Assert.Contains("from", props);
    }

    [Fact]
    public void SetError_Serialization_WithNullOptionalFields_ShouldOmitNulls()
    {
        var error = new SetError
        {
            Type = "notFound"
            // Description and Properties left null
        };

        string json = JsonSerializer.Serialize(error, _jsonOptions);
        var doc = JsonNode.Parse(json)!.AsObject();

        Assert.Equal("notFound", (string?)doc["type"]);
        Assert.False(doc.ContainsKey("description"));
        Assert.False(doc.ContainsKey("properties"));
    }

    [Fact]
    public void SetError_Deserialization_ShouldPopulateProperties()
    {
        const string json = """{"type":"tooLarge","description":"Payload exceeds limit","properties":["body"]}""";
        var error = JsonSerializer.Deserialize<SetError>(json, _jsonOptions)!;

        Assert.Equal("tooLarge", error.Type);
        Assert.Equal("Payload exceeds limit", error.Description);
        Assert.NotNull(error.Properties);
        var props = error.Properties ?? Array.Empty<string>();
        Assert.Single(props);
        Assert.Equal("body", props[0]);
    }

    [Fact]
    public void MethodError_Serialization_WithoutDescription_ShouldOmitDescription()
    {
        var error = new MethodError
        {
            Type = "unknownMethod"
            // Description left null
        };

        string json = JsonSerializer.Serialize(error, _jsonOptions);
        var doc = JsonNode.Parse(json)!.AsObject();

        Assert.Equal("unknownMethod", (string?)doc["type"]);
        Assert.False(doc.ContainsKey("description"));
    }

    [Fact]
    public void MethodError_Deserialization_WithDescription_ShouldPopulate()
    {
        const string json = """{"type":"invalidArguments","description":"Missing required field"}""";
        var error = JsonSerializer.Deserialize<MethodError>(json, _jsonOptions)!;

        Assert.Equal("invalidArguments", error.Type);
        Assert.Equal("Missing required field", error.Description);
    }

    [Fact]
    public void ResultReference_Serialization_ShouldMatchJson()
    {
        var reference = new ResultReference
        {
            ResultOf = "c1",
            Name = "list",
            Path = "/ids/*"
        };

        string json = JsonSerializer.Serialize(reference, _jsonOptions);
        var doc = JsonNode.Parse(json)!.AsObject();

        Assert.Equal("c1", (string?)doc["resultOf"]);
        Assert.Equal("list", (string?)doc["name"]);
        Assert.Equal("/ids/*", (string?)doc["path"]);
    }

    [Fact]
    public void ResultReference_Deserialization_ShouldPopulateAllFields()
    {
        const string json = """{"resultOf":"c2","name":"created","path":"/newId"}""";
        var reference = JsonSerializer.Deserialize<ResultReference>(json, _jsonOptions)!;

        Assert.Equal("c2", reference.ResultOf);
        Assert.Equal("created", reference.Name);
        Assert.Equal("/newId", reference.Path);
    }

    [Fact]
    public void JmapProtocolException_MessageFallback_UsesDescriptionWhenProvided()
    {
        var ex = new JmapProtocolException("unknownMethod", description: "Method not recognized");
        Assert.Equal("Method not recognized", ex.Message);
        Assert.Equal("unknownMethod", ex.ErrorType);
        Assert.Equal("Method not recognized", ex.Description);
    }

    [Fact]
    public void JmapProtocolException_MessageFallback_UsesErrorTypeWhenDescriptionMissing()
    {
        var ex = new JmapProtocolException("invalidArguments");
        Assert.Equal("invalidArguments", ex.Message);
        Assert.Equal("invalidArguments", ex.ErrorType);
        Assert.Null(ex.Description);
    }

    [Fact]
    public void JmapNetworkException_InheritsFrom_JmapException()
    {
        var inner = new InvalidOperationException("inner");
        var ex = new JmapNetworkException("Network failure", inner);
        Assert.IsAssignableFrom<JmapException>(ex);
        Assert.Equal("Network failure", ex.Message);
        Assert.Same(inner, ex.InnerException);
    }
}
